beatstream_dbt:
  outputs:
    dev:
      dataset: dbt_pk
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: dbt-demo-422300
      threads: 1
      type: bigquery
      impersonate_service_account: dbtservacct@dbt-demo-422300.iam.gserviceaccount.com
  target: dev
